#ifndef PURGE_INCLUDE_H
#define PURGE_INCLUDE_H 1

#include "TrackedObject.h"
#include "Math/Degree.h"
#include "Math/Radian.h"
#include "Math/Angle.h"
#include "Math/Vector3.h"
#include "Math/Quaternion.h"
#include "Space/SceneNode.h"
#include "Space/FluentSceneNode.h"
#include "Space/CoordinateSystem.h"
#include "Graphics/Model.h"
#include "Graphics/ModelNode.h"
#include "Graphics/ModelDefinition.h"
#include "Graphics/Camera.h"
#include "Graphics/CameraNode.h"
#include "Graphics/CameraDefinition.h"
#include "Graphics/Window.h"
#include "Graphics/Color.h"
#include "Graphics/Light.h"
#include "Graphics/AmbientLight.h"
#include "Graphics/SpotLight.h"
#include "Graphics/SpotLightDefinition.h"
#include "Graphics/SpotLightNode.h"
#include "Graphics/PointLight.h"
#include "Graphics/PointLightDefinition.h"
#include "Graphics/PointLightNode.h"
#include "Graphics/Renderer.h"
#include "Loop/Task.h"
#include "Loop/TaskGroup.h"
#include "Loop/MainTaskGroup.h"
#include "Loop/RenderingStartTask.h"
#include "Loop/RenderingFinishTask.h"
#include "Loop/FpsPrintTask.h"
#include "Loop/SceneNodeModificationTask.h"

#endif /* PURGE_INCLUDE_H */

